*=$8000
icepalace_stream0:
                .binary "build/icepalace.streams.0.vgc"
icepalace_stream1:
                .binary "build/icepalace.streams.1.vgc"
icepalace_stream3:
                .binary "build/icepalace.streams.3.vgc"
icepalace_stream4:
                .binary "build/icepalace.streams.4.vgc"
icepalace_stream7:
                .binary "build/icepalace.streams.7.vgc"
                .cerror *>$c000,"bank 4 overflow"
                