                .include "submodules/beeb/include/beeb.s65"
                .include "build/vgcplayer_inc.s65"
                .include "build/synerg2_bank4.sym"
                .include "build/synerg2_bank5.sym"
                .include "build/synerg2_bank6.sym"
                .include "build/synerg2_bank7.sym"
                .include "build/synerg2_main.sym"

;-------------------------------------------------------------------------

*=vgcplayer_zp_end
                .dsection zp
                .cerror $>$fc,'zp overrun'

*=$1500
                .dsection code
                .cerror *>$4000,'code overrun'

;-------------------------------------------------------------------------

                .section zp
vsync_count:
                .fill 1
                .send zp

;-------------------------------------------------------------------------

                .section code

main:
                sta $fffe       ;start b2 trace

                lda #0
                sta vsync_count
                
                sec             ;looped playback
                lda #$74        ;2 KB buffer
                ldx #<vgc
                ldy #>vgc
                jsr vgm_init

                sei
                
loop:
                lda #2
-
                bit $fe4d
                beq -

                sta $fe4d

                lda #1
                jsr vgm_update

                inc vsync_count
                lda vsync_count
                cmp #50
                bcc loop

                sta $ffff       ;stop b2 trace

                jmp loop
                
                rts

; u_loader_stream0:
;                 .binary "build/U_LOADER.streams.0.vgc"
; u_loader_stream1:
;                 .binary "build/U_LOADER.streams.1.vgc"
; u_loader_stream2:
;                 .binary "build/U_LOADER.streams.2.vgc"
; u_loader_stream3:
;                 .binary "build/U_LOADER.streams.3.vgc"
; u_loader_stream4:
;                 .binary "build/U_LOADER.streams.4.vgc"
; u_loader_stream5:
;                 .binary "build/U_LOADER.streams.5.vgc"
; u_loader_stream6:
;                 .binary "build/U_LOADER.streams.6.vgc"
; u_loader_stream7:
;                 .binary "build/U_LOADER.streams.7.vgc"

; vgc:
;                 .binary "build/U_LOADER.streams.vgc"
;                 .byte 4
;                 .word u_loader_stream0
;                 .byte 4
;                 .word u_loader_stream1
;                 .byte 4
;                 .word u_loader_stream2
;                 .byte 4
;                 .word u_loader_stream3
;                 .byte 4
;                 .word u_loader_stream4
;                 .byte 4
;                 .word u_loader_stream5
;                 .byte 4
;                 .word u_loader_stream6
;                 .byte 4
;                 .word u_loader_stream7

vgc:
                .binary "build/SYNERG2.streams.vgc"

                .byte 4
                .word synerg2_stream0

                .byte 5
                .word synerg2_stream1

                .byte 6
                .word synerg2_stream2

                .byte 7
                .word synerg2_stream3

                .byte 4         ;main RAM - so any will do
                .word synerg2_stream4

                .byte 6
                .word synerg2_stream5

                .byte 5
                .word synerg2_stream6

                .byte 7
                .word synerg2_stream7
                
                .send code

;-------------------------------------------------------------------------
