                .include "submodules/beeb/include/beeb.s65"
                .include "build/vgcplayer_inc.s65"

;-------------------------------------------------------------------------

*=vgcplayer_zp_end
                .dsection zp

*=$1100
                .dsection code

;-------------------------------------------------------------------------

                .section zp
                .send zp

;-------------------------------------------------------------------------

                .section code

main:
                lda #65
                jsr oswrch
                rts
                .send code

;-------------------------------------------------------------------------
